# Generated by Django 5.1.3 on 2024-11-25 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_person_remove_users_name_users_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_name',
        ),
    ]
