# Generated by Django 5.1.3 on 2024-12-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('idpengguna', models.BigAutoField(default=1, primary_key=True, serialize=False)),
                ('username', models.CharField(default='John Doe', max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('poin', models.IntegerField(default=0)),
                ('hobi', models.TextField(blank=True)),
                ('pekerjaan', models.TextField(blank=True, max_length=100)),
                ('alamat', models.TextField(blank=True)),
                ('foto_profil', models.ImageField(blank=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
