# Generated by Django 5.1.3 on 2024-12-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lokasi',
            field=models.CharField(max_length=50),
        ),
    ]
