# Generated by Django 5.1.3 on 2024-12-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='Lokasi',
        ),
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.AddField(
            model_name='users',
            name='alamat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='users',
            name='foto_profil',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='users',
            name='hobi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='users',
            name='idpengguna',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='users',
            name='pekerjaan',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='poin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='John Doe', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
