# Generated by Django 5.1.3 on 2024-12-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_location_lokasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='idlocation',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
