# Generated by Django 5.1.3 on 2024-12-11 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_remove_restoran_idpengguna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='idpengguna',
        ),
        migrations.AddField(
            model_name='event',
            name='idrestoran',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crud.restoran'),
        ),
    ]
