# Generated by Django 5.1.3 on 2024-12-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_menu_foto_alter_rating_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='foto',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='foto_profil',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='images/'),
        ),
    ]
