# Generated by Django 5.1.3 on 2024-12-11 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_remove_event_idpengguna_event_idrestoran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='idrestoran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.restoran'),
        ),
    ]
