# Generated by Django 5.1.3 on 2024-12-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_users_foto_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Deskripsi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='users',
            name='foto_background',
            field=models.ImageField(blank=True, default='images/default.jpg', upload_to='images/'),
        ),
    ]
